<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumniSeeder extends Seeder
{
    public function run()
    {
        DB::table('alumni')->insert([
            [
                'nama' => 'Andi Saputra',
                'nim' => '20180001',
                'tahun_yudisium' => 2022,
                'tahun_lulus' => 2022,
                'periode_wisuda' => 'Periode I',
                'pekerjaan' => 'Software Engineer',
                'perusahaan' => 'PT Telkom Indonesia',
                'bidang' => 'Teknologi Informasi',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi Hartono',
                'nim' => '20180002',
                'tahun_yudisium' => 2022,
                'tahun_lulus' => 2022,
                'periode_wisuda' => 'Periode II',
                'pekerjaan' => 'Guru',
                'perusahaan' => 'SMA Negeri 1',
                'bidang' => 'Pendidikan',
                'relevansi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Lestari',
                'nim' => '20180003',
                'tahun_yudisium' => 2021,
                'tahun_lulus' => 2021,
                'periode_wisuda' => 'Periode I',
                'pekerjaan' => 'Marketing',
                'perusahaan' => 'Shopee Indonesia',
                'bidang' => 'Bisnis',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dian Permata',
                'nim' => '20180004',
                'tahun_yudisium' => 2023,
                'tahun_lulus' => 2023,
                'periode_wisuda' => 'Periode III',
                'pekerjaan' => null,
                'perusahaan' => null,
                'bidang' => null,
                'relevansi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eko Prasetyo',
                'nim' => '20180005',
                'tahun_yudisium' => 2021,
                'tahun_lulus' => 2021,
                'periode_wisuda' => 'Periode II',
                'pekerjaan' => 'Data Analyst',
                'perusahaan' => 'Gojek',
                'bidang' => 'Teknologi Informasi',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fitri Ayu',
                'nim' => '20180006',
                'tahun_yudisium' => 2020,
                'tahun_lulus' => 2020,
                'periode_wisuda' => 'Periode I',
                'pekerjaan' => 'Wirausaha',
                'perusahaan' => 'Fitri Cake',
                'bidang' => 'Kuliner',
                'relevansi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Gilang Ramadhan',
                'nim' => '20180007',
                'tahun_yudisium' => 2023,
                'tahun_lulus' => 2023,
                'periode_wisuda' => 'Periode II',
                'pekerjaan' => 'UI/UX Designer',
                'perusahaan' => 'Bukalapak',
                'bidang' => 'Teknologi Informasi',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hani Safitri',
                'nim' => '20180008',
                'tahun_yudisium' => 2020,
                'tahun_lulus' => 2020,
                'periode_wisuda' => 'Periode III',
                'pekerjaan' => null,
                'perusahaan' => null,
                'bidang' => null,
                'relevansi' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Indra Kurniawan',
                'nim' => '20180009',
                'tahun_yudisium' => 2022,
                'tahun_lulus' => 2022,
                'periode_wisuda' => 'Periode I',
                'pekerjaan' => 'System Administrator',
                'perusahaan' => 'Bank BRI',
                'bidang' => 'Perbankan',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Joko Santoso',
                'nim' => '20180010',
                'tahun_yudisium' => 2021,
                'tahun_lulus' => 2021,
                'periode_wisuda' => 'Periode II',
                'pekerjaan' => 'Customer Support',
                'perusahaan' => 'Tokopedia',
                'bidang' => 'Teknologi Informasi',
                'relevansi' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
